### ISSUE TITLE
Consolidate and update GitHub workflows

### ISSUE THREAD

**Issue by tianyizheng02** [Pitt-CSC/PittAPI#175]
Two potential to-dos regarding our GitHub workflows:
- [ ] We currently have two workflows, `autotest.yml` and `tests-on-push.yml`, but both run the same jobs. Is it OK to consolidate the two workflows as follows? I'd very much welcome thoughts/comments from other maintainers as to whether this would pose any issues.
    ```yaml
    on:
      push:
        branches: [ "dev" ]
      pull_request:
        branches: [ "dev" ]
      schedule:
        - cron: '00 12 1 * *'
    ```
- [ ] Our workflows currently use Node.js 16 actions, [which are deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Every workflow run has an annotation notifying us of this (see [this one](https://github.com/pittcsc/PittAPI/actions/runs/9330086321) for an example):
    ```
    run-test-suite
    Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
    ```
    Resolving these warnings should be as simple as updating `actions/checkout` and `actions/setup-python` to their latest versions.
